create table messages (
  id bigint generated by default as identity primary key,
  session_id uuid references sessions(id) on delete cascade,
  role text not null, -- 'user' or 'assistant'
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
